#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec  2 07:37:55 2018

@author: ravindra
"""

for x in range(2000, 3201):
    if (x%7)==0:
        y=x/5.0
        if (y%5)!=0:print(str(x), end =",")